name: Publish Development Docker

on:
  schedule:
    # Publish a weekly new image to capture any updates from libraries.
    - cron: "0 1 * * 0" # every Sunday at 1am
  push:
    # Publish a new image whenever changes detected in main.
    branches:
      - master
    paths:
      - ".devcontainer/**"
      - "installers/**"
      - "requirements.txt"
  workflow_dispatch:

env:
  PLATFORMS: "linux/amd64"
  # Use the below platforms to enable MacOSX builds for Docker.
  # PLATFORMS: "linux/amd64,linux/arm64"

# Make sure we have concurrency per workflow per branch. Cancel any previous ones.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-to-docker-hub:
    name: Build and push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      # Enable this section if we need MacOSX builds for Docker.
      # --------------------------------------------------------------
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # --------------------------------------------------------------
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.INGENII_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.INGENII_DOCKER_HUB_PASSWORD }}
      -
        name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          file: .devcontainer/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ingeniisolutions/dataminedev-runtime:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
